In [133]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
datapath = "../data/data/v2.0/"
import csv
from collections import defaultdict
# code\data\data\v2.0\hipe2020\en\HIPE-2022-v2.0-hipe2020-dev-en.tsv

In [2]:
maxInt = sys.maxsize

while True:
    # decrease the maxInt value by factor 10 
    # as long as the OverflowError occurs.

    try:
        csv.field_size_limit(maxInt)
        break
    except OverflowError:
        maxInt = int(maxInt/10)

In [46]:
test_dataframe = pd.read_csv(datapath+"hipe2020/en/HIPE-2022-v2.0-hipe2020-dev-en.tsv", sep = '\t', header = 0, engine="python", comment='#', na_values=['_'], quoting=csv.QUOTE_NONE)
test_dataframe

TOKEN NE-COARSE-LIT NE-COARSE-METO  NE-FINE-LIT  NE-FINE-METO  \
0          From             O              O          NaN           NaN   
1           the             O              O          NaN           NaN   
2      AMERICAN        B-prod              O          NaN           NaN   
3       MERCURY        I-prod              O          NaN           NaN   
4             .             O              O          NaN           NaN   
...         ...           ...            ...          ...           ...   
29054     Booth             O              O          NaN           NaN   
29055        of             O              O          NaN           NaN   
29056    course             O              O          NaN           NaN   
29057         )             O              O          NaN           NaN   
29058         .             O              O          NaN           NaN   

       NE-FINE-COMP  NE-NESTED NEL-LIT NEL-METO                     MISC  
0               NaN        NaN     NaN      NaN                      NaN  
1               NaN        NaN     NaN      NaN                      NaN  
2               NaN        NaN     NIL      NaN                      NaN  
3               NaN        NaN     NIL      NaN             NoSpaceAfter  
4               NaN        NaN     NaN      NaN  EndOfLine|EndOfSentence  
...             ...        ...     ...      ...                      ...  
29054           NaN        NaN     NaN      NaN                      NaN  
29055           NaN        NaN     NaN      NaN                      NaN  
29056           NaN        NaN     NaN      NaN             NoSpaceAfter  
29057           NaN        NaN     NaN      NaN             NoSpaceAfter  
29058           NaN        NaN     NaN      NaN  EndOfLine|EndOfSentence  

[29059 rows x 10 columns]

In [47]:
test_NE = test_dataframe[test_dataframe["NE-COARSE-LIT"] != "O"]
test_dataframe["TOKEN"] = test_dataframe["TOKEN"].str.lower()

In [91]:
test_NE[test_NE["TOKEN"] == "¬"]

TOKEN NE-COARSE-LIT NE-COARSE-METO  NE-FINE-LIT  NE-FINE-METO  \
1627      ¬         I-loc              O          NaN           NaN   
2505      ¬         I-loc              O          NaN           NaN   
2865      ¬        I-pers              O          NaN           NaN   
3378      ¬         I-loc              O          NaN           NaN   
3587      ¬        I-pers              O          NaN           NaN   
...     ...           ...            ...          ...           ...   
26918     ¬        I-pers              O          NaN           NaN   
27295     ¬         I-loc              O          NaN           NaN   
27788     ¬         I-loc              O          NaN           NaN   
28670     ¬         I-org              O          NaN           NaN   
28676     ¬         I-loc          I-loc          NaN           NaN   

       NE-FINE-COMP  NE-NESTED    NEL-LIT  NEL-METO       MISC  
1627            NaN        NaN        Q30       NaN  EndOfLine  
2505            NaN        NaN        NIL       NaN  EndOfLine  
2865            NaN        NaN    Q151321       NaN  EndOfLine  
3378            NaN        NaN     Q18383       NaN  EndOfLine  
3587            NaN        NaN    Q550690       NaN  EndOfLine  
...             ...        ...        ...       ...        ...  
26918           NaN        NaN  Q30088046       NaN  EndOfLine  
27295           NaN        NaN     Q59174       NaN  EndOfLine  
27788           NaN        NaN   Q2168889       NaN  EndOfLine  
28670           NaN        NaN        NIL       NaN  EndOfLine  
28676           NaN        NaN     Q49231  Q1627684  EndOfLine  

[65 rows x 10 columns]

In [53]:
data = test_dataframe["TOKEN"].value_counts()
test = data.to_dict()
data

,           1654
the         1620
.           1343
of          1076
and          737
            ... 
reftored       1
ticulars       1
face           1
$000,0         1
bucket         1
Name: TOKEN, Length: 6392, dtype: int64

In [85]:
B_prods = test_NE["TOKEN"][test_NE["NE-COARSE-LIT"].isin(["B-prod","I-prod"])]
print(len(B_prods))
token_count = B_prods.value_counts()
print(len(token_count))
token_count

97
72


.                4
Guide            4
¬                4
THE              3
Journal          3
                ..
3t               1
England          1
Land             1
Intelligencer    1
MAGNA            1
Name: TOKEN, Length: 72, dtype: int64

In [30]:
# plt.bar(test.keys(),test.values())
# plt.show()
test_2 = {key:val for key, val in test.items() if val > 10}
# print(test_2)
# print(len(test))
print(len(test_2))

264


In [39]:
# plt.figure(figsize=(50,25))
# plt.bar([i*2 for i in range(len(test_2))],test_2.values(), width=0.5)
# plt.xticks([i*2 for i in range(len(test_2))],test_2.keys(), rotation = 90 )
# # plt.show()

In [130]:
test_sum = 0
total = len(test_dataframe)
token_count = 0
token_list = dict()
for key in test:
    token_count += 1
    test_sum += test[key]
    token_list[key] = test[key]
    if test_sum > total * 0.50:
        print(key)
        print(test[key])
        print(token_count)
        print(token_list)
        break

men
34
75
{',': 1654, 'the': 1620, '.': 1343, 'of': 1076, 'and': 737, 'to': 611, 'a': 557, '¬': 539, 'in': 520, 'is': 265, '-': 253, 'that': 214, 'for': 210, 'he': 184, 'be': 173, 'as': 171, 'was': 168, 'it': 167, 'at': 155, 'on': 150, 'by': 148, 'with': 138, 'this': 137, 'will': 127, 'from': 114, 'have': 114, '’': 111, 'his': 107, 'are': 105, 'i': 103, 'their': 102, ';': 100, 'which': 95, 's': 92, 'not': 90, 'they': 85, '*': 81, 'has': 81, '“': 77, "'": 77, 'you': 75, 'or': 74, 'an': 74, 'one': 67, 'all': 66, '”': 65, 'we': 62, 'been': 61, 'but': 59, 'no': 55, 'who': 51, 'our': 47, 'than': 47, 'were': 47, 'other': 46, 'county': 44, '—': 44, 'them': 44, 'any': 44, 'man': 43, 'when': 43, 'made': 43, 'new': 41, 'more': 41, 'j': 39, 'can': 39, 'there': 39, 'out': 39, 'may': 38, 'day': 37, 'would': 37, ':': 36, 'its': 36, 'had': 35, 'men': 34}


In [104]:
NE_COARSE = test_dataframe["NE-COARSE-LIT"]
NE_list = list(pd.unique(NE_COARSE))
NE_list

['O',
 'B-prod',
 'I-prod',
 'B-loc',
 'I-loc',
 'B-org',
 'I-org',
 'B-time',
 'I-time',
 'B-pers',
 'I-pers']

In [176]:
len(test_dataframe.index)

29059

In [185]:
feature_list = list(token_list)
label_list = NE_list

feature_matrix = []
label_matrix = []
# print(np.append(result_matrix,np.zeros(shape=(1,len(token_list))),axis=0))
# result_matrix
pos_dict = defaultdict(lambda: [])
label_dict = defaultdict(lambda: [])
pos = 0
progress = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
for idx in test_dataframe.index:
    if idx/len(test_dataframe) > progress[0]:
        print(progress[0])
        progress.pop(0)
    pos += 1
    row = test_dataframe.iloc[idx]
    token = row["TOKEN"]
    label = row["NE-COARSE-LIT"]

    label_dict[token].append((pos,label))
    
    if token in feature_list:
        pos_dict[token].append(pos)

    if isinstance(row["MISC"], float) or "EndOfSentence" not in row["MISC"]:
        continue

    for key in label_dict:
        for appearance in label_dict[key]:
            pos = appearance[0]
            label_vector = np.zeros(shape=(len(label_list)))
            label_vector[label_list.index(appearance[1])] = 1
            feature_vector = np.zeros(shape=(len(feature_list)))
            for feature in pos_dict:
                nearest_pos = 100 # I assume there is no feature farther than 100 tokens away from current token in a sentance
                for temp_pos in pos_dict[feature]:
                    relative_pos = temp_pos - pos
                    if abs(relative_pos) < nearest_pos:
                        nearest_pos = relative_pos
                    else:
                        continue
                feature_vector[feature_list.index(feature)] = nearest_pos
            feature_matrix.append(feature_vector)
            label_matrix.append(label_vector)           
    pos_dict = defaultdict(lambda: [])
    label_dict = defaultdict(lambda: [])
    pos = 0
            
feature_matrix = np.array(feature_matrix)
label_matrix = np.array(label_matrix)

0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9


In [186]:
print(feature_matrix)
print(len(feature_matrix))

[[  0.   1.   4. ...   0.   0.   0.]
 [  0.   0.   3. ...   0.   0.   0.]
 [  0.  -1.   2. ...   0.   0.   0.]
 ...
 [-58. -23. -86. ...   0. -13.   0.]
 [-59. -24. -87. ...   0. -14.   0.]
 [-60. -25. -88. ...   0. -15.   0.]]
29059


In [187]:
print(label_matrix)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [200]:
training_data = feature_matrix[0:int(len(feature_matrix)*0.8)]
test_data = feature_matrix[int(len(feature_matrix)*0.8):]
training_labels = label_matrix[0:int(len(feature_matrix)*0.8)]
test_labels = label_matrix[int(len(feature_matrix)*0.8):]

In [207]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf.fit(training_data,training_labels)

DecisionTreeClassifier()

In [206]:
tp = 0
fp = 0
fn = 0
tn = 0
total = len(test_data)
prediction = clf.predict(test_data)

for i, pred in enumerate(prediction):
    correct_idx = test_labels[i].index(1)
    if pred[correct_idx] == 1:
        tp += 1
    

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
